### ISSUE TITLE
Crashed when uploading files to an event

### ISSUE THREAD

**Issue by yuruky-nix** [xinfab/fab-manager#7]

**Comment by lpgn** [comment]
i think its fixed can you test again?

**Comment by yuruky-nix** [comment]
Don't know why, my ie and firefox both crashed still. (Maybe it's my own problem...
![2](https://cloud.githubusercontent.com/assets/10483083/12397018/79745162-be45-11e5-8fcd-e98a5dc9734f.PNG)
![3](https://cloud.githubusercontent.com/assets/10483083/12397017/794ccd0e-be45-11e5-9c02-7d77abb48b08.PNG)

**Comment by lpgn** [comment]
funny will try again . I use chrome.can you try with Chrome as well?

**Comment by lpgn** [comment]
by the way it has to be a cad file

**Comment by lpgn** [comment]
like stl or dwg

**Comment by lpgn** [comment]
@lionello trying to drag you here ;-)

**Comment by yuruky-nix** [comment]
Ye, it's a stl that I upload.
Strange that my CentBrowser can't even see the site, totally white.
And my 360jisuBrowser crashed too. (these two browsers are both based on chrome
Thought only the original chrome works,
then it crashed still... for good : (
![5](https://cloud.githubusercontent.com/assets/10483083/12397583/0cda3aea-be49-11e5-9a0b-2ead53499c76.PNG)
![6](https://cloud.githubusercontent.com/assets/10483083/12397581/0cc44000-be49-11e5-909f-bc4ebe7005ce.PNG)
![10](https://cloud.githubusercontent.com/assets/10483083/12397816/8c0178c8-be4a-11e5-8488-c8d15d50795d.PNG)

**Comment by lpgn** [comment]
https://github.com/LaCasemate/fab-manager/issues/17 fixed it

**Comment by lpgn** [comment]
You might want to open a new issue if the cent browser and etc still don't work...
