### ISSUE TITLE
Feature request (larger workshop blocks at FABLAB COURSES AND WORKSHOPS ADD AN EVENT page)

### ISSUE THREAD

**Issue by yuruky-nix** [xinfab/fab-manager#8]

**Comment by lpgn** [comment]
looks big to me can you check again, also give detail on browser you are using
<img width="1434" alt="screenshot 2016-01-18 16 08 41" src="https://cloud.githubusercontent.com/assets/2556951/12396238/36f53938-bdfe-11e5-9c41-b5033d374435.png">

**Comment by yuruky-nix** [comment]
Log in as a member, not the admin, or even not log in, and you'll see:
![Uploading 1.PNG…]()

**Comment by yuruky-nix** [comment]
![1](https://cloud.githubusercontent.com/assets/10483083/12396775/35117032-be44-11e5-8985-dfd554244f92.PNG)

**Comment by lpgn** [comment]
I see what you mean. but I think its fine as you can click and see details, maybe this size is due to to be able to open this on a cellphone as well?
